"""Public, versioned Agent-native control-plane contract."""

from .digest import (
    CanonicalizationError,
    canonical_asset,
    canonical_json,
    canonical_json_bytes,
    canonical_publication_target,
    canonical_sha256,
    canonicalize,
    content_digest,
    content_digest_payload,
    normalize_utc_datetime,
    plan_digest,
    plan_digest_payload,
)
from .schemas import (
    MAX_CONTRACT_REQUEST_BODY_BYTES,
    MAX_CONTRACT_RESPONSE_BODY_BYTES,
    MAX_PERFORMANCE_REVIEW_JOBS,
    MAX_RENDERER_PAYLOAD_BYTES,
    MAX_SIGNED_64,
    MAX_STAGE_ASSETS,
    SCHEMA_VERSION,
    ApprovalAssetDownloadResponse,
    ApprovalContentSnapshot,
    ApprovalDecision,
    ApprovalDecisionRequest,
    ApprovalDecisionResponse,
    ApprovalReviewAsset,
    ApprovalReviewResponse,
    ApprovalReviewTarget,
    ApprovalResponse,
    ApprovalState,
    AssetInput,
    CollectMetricsRequest,
    CollectMetricsResponse,
    JobStatusResponse,
    MetricQuality,
    MetricSnapshot,
    MetricsCollectionState,
    PerformanceReviewItem,
    PerformanceReviewRequest,
    PerformanceReviewResponse,
    PerformanceTotals,
    PlanPublicationRequest,
    PlanPublicationResponse,
    PlanState,
    PostIdentity,
    PublicationTarget,
    RequestApprovalRequest,
    RendererAssetRule,
    RendererBinding,
    RendererContract,
    ScheduleRequest,
    ScheduleResponse,
    ScheduleState,
    StageContentRequest,
    StageContentResponse,
    validate_renderer_contract,
)
from .client import AgentClient, AgentContractClient, ClientError
from .snapshot import approval_content_digest


def __getattr__(name: str):
    """Keep CLI imports configuration-lazy while exposing the Python service."""

    if name in {"AgentContractError", "AgentControlPlane"}:
        from .service import AgentContractError, AgentControlPlane

        return {
            "AgentContractError": AgentContractError,
            "AgentControlPlane": AgentControlPlane,
        }[name]
    raise AttributeError(name)


__all__ = [
    "MAX_CONTRACT_REQUEST_BODY_BYTES",
    "MAX_CONTRACT_RESPONSE_BODY_BYTES",
    "MAX_PERFORMANCE_REVIEW_JOBS",
    "MAX_RENDERER_PAYLOAD_BYTES",
    "MAX_SIGNED_64",
    "MAX_STAGE_ASSETS",
    "SCHEMA_VERSION",
    "ApprovalAssetDownloadResponse",
    "ApprovalContentSnapshot",
    "ApprovalDecision",
    "ApprovalDecisionRequest",
    "ApprovalDecisionResponse",
    "ApprovalReviewAsset",
    "ApprovalReviewResponse",
    "ApprovalReviewTarget",
    "ApprovalResponse",
    "ApprovalState",
    "AgentClient",
    "AgentContractClient",
    "AgentContractError",
    "AgentControlPlane",
    "AssetInput",
    "CanonicalizationError",
    "ClientError",
    "CollectMetricsRequest",
    "CollectMetricsResponse",
    "JobStatusResponse",
    "MetricQuality",
    "MetricSnapshot",
    "MetricsCollectionState",
    "PerformanceReviewItem",
    "PerformanceReviewRequest",
    "PerformanceReviewResponse",
    "PerformanceTotals",
    "PlanPublicationRequest",
    "PlanPublicationResponse",
    "PlanState",
    "PostIdentity",
    "PublicationTarget",
    "RequestApprovalRequest",
    "RendererAssetRule",
    "RendererBinding",
    "RendererContract",
    "ScheduleRequest",
    "ScheduleResponse",
    "ScheduleState",
    "StageContentRequest",
    "StageContentResponse",
    "validate_renderer_contract",
    "canonical_asset",
    "approval_content_digest",
    "canonical_json",
    "canonical_json_bytes",
    "canonical_publication_target",
    "canonical_sha256",
    "canonicalize",
    "content_digest",
    "content_digest_payload",
    "normalize_utc_datetime",
    "plan_digest",
    "plan_digest_payload",
]
