"""Stateless stdio MCP bridge for the Agent contract v1 HTTP API.

The bridge deliberately owns no control-plane state.  It never imports the
database, domain service, legacy administrator API, or a Publisher.  Every tool
call creates a short-lived :class:`AgentContractClient`, forwards the request to
the versioned HTTP API, and returns the already-validated v1 DTO.

Only Agent-principal operations are exposed.  Human approval review, asset
download, and approval decisions stay on the separate human credential surface.
"""

from __future__ import annotations

from collections.abc import Callable
import json
import os
from typing import Annotated, Any, Literal, TypeVar

from mcp.server import MCPServer
from mcp.types import CallToolResult, TextContent, ToolAnnotations
from pydantic import BaseModel, ConfigDict, Field, TypeAdapter, ValidationError

from ai_ops import __version__

from .client import AgentContractClient, ClientError, DEFAULT_AGENT_API_URL
from .schemas import (
    MAX_CONTRACT_REQUEST_BODY_BYTES,
    ApprovalResponse,
    CollectMetricsRequest,
    CollectMetricsResponse,
    JobStatusResponse,
    PerformanceReviewRequest,
    PerformanceReviewResponse,
    PlanPublicationRequest,
    PlanPublicationResponse,
    RequestApprovalRequest,
    ScheduleRequest,
    ScheduleResponse,
    StageContentRequest,
    StageContentResponse,
)


TOKEN_ENV = "AI_OPS_TOKEN"
URL_ENV = "AI_OPS_URL"

# MCP requires an object at the root of structuredContent for older negotiated
# protocol revisions.  The concrete value is still validated by the existing
# response DTO before it crosses this boundary.
StructuredResult = Annotated[CallToolResult, dict[str, object]]
ResponseT = TypeVar("ResponseT", bound=BaseModel)
IdempotencyKey = Annotated[
    str,
    Field(
        min_length=8,
        max_length=128,
        pattern=r"^[A-Za-z0-9][A-Za-z0-9._:-]{7,127}$",
        description="Caller-supplied Agent contract idempotency key; never generated by MCP.",
    ),
]
JobIdentifier = Annotated[int, Field(gt=0, description="Durable publication job ID.")]


class _StrictToolInput(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)


class _MCPErrorDetail(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    code: str = Field(pattern=r"^[a-z][a-z0-9_]{0,63}$")
    message: str = Field(min_length=1, max_length=1000)


class _MCPErrorEnvelope(BaseModel):
    """Strict v1 error branch advertised by every MCP tool output schema."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    schema_version: Literal[1] = 1
    error: _MCPErrorDetail


class _StageContentInput(_StrictToolInput):
    request: StageContentRequest
    idempotency_key: IdempotencyKey


class _PlanPublicationInput(_StrictToolInput):
    request: PlanPublicationRequest
    idempotency_key: IdempotencyKey


class _RequestApprovalInput(_StrictToolInput):
    request: RequestApprovalRequest
    idempotency_key: IdempotencyKey


class _ScheduleInput(_StrictToolInput):
    request: ScheduleRequest
    idempotency_key: IdempotencyKey


class _GetJobStatusInput(_StrictToolInput):
    job_id: JobIdentifier


class _CollectMetricsInput(_StrictToolInput):
    request: CollectMetricsRequest
    idempotency_key: IdempotencyKey


class _ReviewPerformanceInput(_StrictToolInput):
    request: PerformanceReviewRequest


_TOOL_INPUT_TYPES: dict[str, type[_StrictToolInput]] = {
    "stage_content": _StageContentInput,
    "plan_publication": _PlanPublicationInput,
    "request_approval": _RequestApprovalInput,
    "schedule": _ScheduleInput,
    "get_job_status": _GetJobStatusInput,
    "collect_metrics": _CollectMetricsInput,
    "review_performance": _ReviewPerformanceInput,
}

_TOOL_RESPONSE_TYPES: dict[str, type[BaseModel]] = {
    "stage_content": StageContentResponse,
    "plan_publication": PlanPublicationResponse,
    "request_approval": ApprovalResponse,
    "schedule": ScheduleResponse,
    "get_job_status": JobStatusResponse,
    "collect_metrics": CollectMetricsResponse,
    "review_performance": PerformanceReviewResponse,
}


def _output_schema(response_type: type[BaseModel]) -> dict[str, object]:
    """Describe the exact success-or-error structured result union."""

    schema = TypeAdapter(response_type | _MCPErrorEnvelope).json_schema()
    # These object shapes are disjoint and individually deny extra properties.
    # ``oneOf`` makes that closed union explicit to MCP clients.
    schema["oneOf"] = schema.pop("anyOf")
    schema["type"] = "object"
    schema["title"] = f"{response_type.__name__}OrError"
    return schema


class AgentMCPServer(MCPServer):
    """MCPServer with strict, redacted validation for the public tool envelope."""

    async def list_tools(self):
        tools = await super().list_tools()
        strict_tools = []
        for tool in tools:
            input_type = _TOOL_INPUT_TYPES.get(tool.name)
            response_type = _TOOL_RESPONSE_TYPES.get(tool.name)
            if input_type is None or response_type is None:  # pragma: no cover - registration guard
                strict_tools.append(tool)
                continue
            strict_tools.append(
                tool.model_copy(
                    update={
                        "input_schema": input_type.model_json_schema(),
                        "output_schema": _output_schema(response_type),
                    }
                )
            )
        return strict_tools

    async def call_tool(self, name: str, arguments: dict[str, Any], context=None):
        input_type = _TOOL_INPUT_TYPES.get(name)
        if input_type is not None:
            try:
                encoded = json.dumps(
                    arguments,
                    ensure_ascii=False,
                    separators=(",", ":"),
                ).encode("utf-8")
                if len(encoded) > MAX_CONTRACT_REQUEST_BODY_BYTES:
                    raise ValueError("MCP tool request is too large")
                input_type.model_validate_json(encoded, strict=True)
            except (TypeError, ValueError, ValidationError):
                # Pydantic validation messages include rejected input values.
                # Keep content bodies, local paths, and arbitrary extras out of
                # the Agent-visible error surface.
                return _client_failure(
                    "invalid_request",
                    "MCP tool arguments do not match the versioned Agent contract",
                )
        return await super().call_tool(name, arguments, context)


_ADDITIVE_IDEMPOTENT = ToolAnnotations(
    read_only_hint=False,
    destructive_hint=False,
    idempotent_hint=True,
    open_world_hint=False,
)
_READ_ONLY = ToolAnnotations(
    read_only_hint=True,
    destructive_hint=False,
    idempotent_hint=True,
    open_world_hint=False,
)
_METRICS_WRITE = ToolAnnotations(
    read_only_hint=False,
    destructive_hint=False,
    idempotent_hint=True,
    open_world_hint=True,
)


server = AgentMCPServer(
    name="ai-ops-auto",
    title="AI Ops Auto Creator Operations Control Plane",
    description="Governed Agent contract v1 tools over the existing AI Ops Auto HTTP API.",
    instructions=(
        "Use these tools to stage, plan, request approval, schedule, observe, and review creator "
        "operations. Human approval tools are intentionally absent. Scheduling creates durable "
        "jobs and can lead to real publication later when an operator enables the worker."
    ),
    version=__version__,
    log_level="WARNING",
)


def _compact_json(payload: dict[str, object]) -> str:
    return json.dumps(payload, ensure_ascii=False, separators=(",", ":"), sort_keys=True)


def _result(payload: dict[str, object], *, is_error: bool = False) -> CallToolResult:
    """Return matching structured and text forms for old and new MCP clients."""

    return CallToolResult(
        content=[TextContent(type="text", text=_compact_json(payload))],
        structured_content=payload,
        is_error=is_error,
    )


def _client_failure(code: str, message: str) -> CallToolResult:
    envelope = _MCPErrorEnvelope(
        error=_MCPErrorDetail(code=code, message=message),
    )
    return _result(envelope.model_dump(mode="json"), is_error=True)


def _invoke(
    operation: Callable[[AgentContractClient], ResponseT],
    response_type: type[ResponseT],
) -> CallToolResult:
    """Invoke one HTTP operation with a fresh client and a redacted error surface."""

    token = os.environ.get(TOKEN_ENV)
    if not token:
        return _client_failure(
            "missing_token",
            f"{TOKEN_ENV} environment variable is required",
        )

    client: AgentContractClient | None = None
    try:
        client = AgentContractClient(
            base_url=os.environ.get(URL_ENV, DEFAULT_AGENT_API_URL),
            token=token,
        )
        response = operation(client)
        if not isinstance(response, response_type):
            return _client_failure(
                "invalid_response",
                "Agent API client returned an invalid contract response",
            )
        return _result(response.model_dump(mode="json"))
    except ClientError as exc:
        try:
            envelope = _MCPErrorEnvelope.model_validate(exc.to_dict(), strict=True)
        except ValidationError:
            return _client_failure("client_failure", "Agent API MCP tool failed")
        return _result(envelope.model_dump(mode="json"), is_error=True)
    except Exception:
        # Never copy exception text across the Agent boundary: transport
        # exceptions can include URLs, request data, headers, or local paths.
        return _client_failure("client_failure", "Agent API MCP tool failed")
    finally:
        if client is not None:
            try:
                client.close()
            except Exception:
                pass


@server.tool(
    title="Stage content",
    description=(
        "Store an immutable Agent contract v1 content snapshot through the HTTP control plane. "
        "Requires content:stage and an explicit idempotency key."
    ),
    annotations=_ADDITIVE_IDEMPOTENT,
)
def stage_content(
    request: StageContentRequest,
    idempotency_key: IdempotencyKey,
) -> StructuredResult:
    return _invoke(
        lambda client: client.stage_content(request, idempotency_key),
        StageContentResponse,
    )


@server.tool(
    title="Plan publication",
    description=(
        "Bind exact content, target accounts, renderer projections, and timing in a v1 plan. "
        "Requires plan:create and an explicit idempotency key."
    ),
    annotations=_ADDITIVE_IDEMPOTENT,
)
def plan_publication(
    request: PlanPublicationRequest,
    idempotency_key: IdempotencyKey,
) -> StructuredResult:
    return _invoke(
        lambda client: client.plan_publication(request, idempotency_key),
        PlanPublicationResponse,
    )


@server.tool(
    title="Request human approval",
    description=(
        "Create a human approval request for an exact v1 publication plan. This tool cannot read "
        "or decide the approval. Requires approval:request and an explicit idempotency key."
    ),
    annotations=_ADDITIVE_IDEMPOTENT,
)
def request_approval(
    request: RequestApprovalRequest,
    idempotency_key: IdempotencyKey,
) -> StructuredResult:
    return _invoke(
        lambda client: client.request_approval(request, idempotency_key),
        ApprovalResponse,
    )


@server.tool(
    title="Schedule approved publication",
    description=(
        "Create durable jobs for an independently approved v1 plan. This HTTP call does not "
        "publish directly, but the jobs can later cause real external publication when an operator "
        "runs the worker with automatic publishing enabled. Requires schedule:create and an "
        "explicit idempotency key."
    ),
    annotations=_ADDITIVE_IDEMPOTENT,
)
def schedule(
    request: ScheduleRequest,
    idempotency_key: IdempotencyKey,
) -> StructuredResult:
    return _invoke(
        lambda client: client.schedule(request, idempotency_key),
        ScheduleResponse,
    )


@server.tool(
    title="Get publication job status",
    description=(
        "Read the durable, credential-free status projection for one publication job. "
        "Requires job:read."
    ),
    annotations=_READ_ONLY,
)
def get_job_status(job_id: JobIdentifier) -> StructuredResult:
    return _invoke(lambda client: client.get_job_status(job_id), JobStatusResponse)


@server.tool(
    title="Collect publication metrics",
    description=(
        "Read metrics from the selected external platform when supported and persist one normalized "
        "snapshot. This is an open-world write, not a read-only query. Requires metrics:collect and "
        "an explicit idempotency key."
    ),
    annotations=_METRICS_WRITE,
)
def collect_metrics(
    request: CollectMetricsRequest,
    idempotency_key: IdempotencyKey,
) -> StructuredResult:
    return _invoke(
        lambda client: client.collect_metrics(request, idempotency_key),
        CollectMetricsResponse,
    )


@server.tool(
    title="Review publication performance",
    description=(
        "Read a bounded, normalized performance review for selected durable jobs. "
        "Requires performance:read."
    ),
    annotations=_READ_ONLY,
)
def review_performance(request: PerformanceReviewRequest) -> StructuredResult:
    return _invoke(
        lambda client: client.review_performance(request),
        PerformanceReviewResponse,
    )


def main() -> None:
    """Run the dedicated MCP process over stdio."""

    server.run(transport="stdio")


__all__ = [
    "TOKEN_ENV",
    "URL_ENV",
    "collect_metrics",
    "get_job_status",
    "main",
    "plan_publication",
    "request_approval",
    "review_performance",
    "schedule",
    "server",
    "stage_content",
]
