"""add publish_jobs.superseded_by_job_id — 重发覆盖追踪字段（publishing-sop §五）。

Revision ID: 7c183c0ba12a
Revises: b09fbf0bf0f0
Create Date: 2026-05-18 16:35:45.840483

新增 publish_jobs.superseded_by_job_id (self-FK, nullable)：
  - 旧 PublishJob 失败 / 内容错重发时，新 job.id 写入旧 job 的此字段
  - 后台 UI / 周报据此追踪"被覆盖"的 job，运营复盘有据
  - nullable=True 兼容存量数据：默认 None 表示"未被覆盖"

实现细节：
  SQLite ALTER TABLE 不能 add column + FK，必须走 batch_alter_table
  （render_as_batch=True 在 env.py 已配置，autogenerate 自动生成 batch 块）。
  FK constraint 命名 fk_publish_jobs_superseded_by_job_id，方便 downgrade
  在 Postgres / 其他强约束 DB 上明确 drop。
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c183c0ba12a'
down_revision: Union[str, None] = 'b09fbf0bf0f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publish_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('superseded_by_job_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_publish_jobs_superseded_by_job_id',
            'publish_jobs',
            ['superseded_by_job_id'],
            ['id'],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publish_jobs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_publish_jobs_superseded_by_job_id', type_='foreignkey')
        batch_op.drop_column('superseded_by_job_id')

    # ### end Alembic commands ###
