"""add metrics.source — 采集来源标签字段（Round 6 / TD-Z3-followup-2 / TD-P0-debt2）。

Revision ID: 7c7c50aecd6a
Revises: 7c183c0ba12a
Create Date: 2026-05-19 01:01:20.768424

新增 metrics.source (VARCHAR(16), NOT NULL, server_default='scheduled')：
  - "initial"   = worker._persist_initial_metrics 落第一份发布快照
  - "scheduled" = scheduler/metrics.collect_one 飞轮采集（1h/24h/7d 档位）
  - "manual"    = api/main.py /jobs/{id}/collect 端点手动触发
  - 预留：external / backfill

owner 价值：让 24h 健康度评估触发判定从隐式（按计数 / 时间窗反推）升级到
显式（按 source 计数）——任何后续给 Metrics 加写入入口都不污染触发判定。
详见 src/ai_ops/scheduler/metrics.py 三段优先级触发判定块。

实现细节：
  SQLite ALTER TABLE 不能 add column WITHOUT default + NOT NULL，必须走
  batch_alter_table（render_as_batch=True 在 env.py 已配置，autogenerate
  自动生成 batch 块）。server_default='scheduled' 让 ALTER 时存量行被填
  默认值，避免 NOT NULL 违反。

数据迁移说明（无单独 data migration）：
  老 Metrics 行被 server_default 一刀切填为 "scheduled"——如其中混着
  initial 行（worker 已接入 _persist_initial_metrics 的窗口期），下次该 job
  跑飞轮采集时 source-based 判定会"提前"。但 scheduler/metrics.py 加了
  cutoff 兜底（优先级 3）：当表中所有 metric source 都相同时降级旧 cutoff 逻辑，
  迁移窗口期不会误触发健康评估。新数据陆续写入后自然过渡到 source-based 路径。
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c7c50aecd6a'
down_revision: Union[str, None] = '7c183c0ba12a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=16), server_default='scheduled', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
